apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mesreltime
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - deploy-web.yaml
  - deploy-api-gateway.yaml
  - deploy-auth.yaml
  - deploy-messaging.yaml
  - deploy-notification.yaml
  - deploy-media.yaml
  - deploy-worker.yaml
  - services.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml