apiVersion: v1
kind: Secret
metadata:
  name: mesreltime-secrets
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "replace-with-strong-secret"
  JWT_REFRESH_SECRET: "replace-with-strong-secret"
  S3_ACCESS_KEY: "replace"
  S3_SECRET_KEY: "replace"